### ISSUE TITLE
File is wiped upon export

### ISSUE THREAD

**Issue by ghost** [codemonkey85/PKMDS-Blazor#13]
Steps to reproduce

1. Upload Pokémon White 2.dsv save file using google chrome at pkmds.app on an android phone

2. Make any edit

3. Hit save on your edits

4. Export save file

5. Move the save file to the correct location

6. Try running the game via emulator

7. Save file is wiped empty

**Comment by codemonkey85** [comment]
Thanks for the report. Would you mind sharing your 'Pokémon White 2.dsv' save file so I can test with it?

**Comment by Luna-Karch** [comment]
Unfortunately I don't think I have it anymore, honestly didn't expect a reply, but I did supply my exact steps to replicate the problem, the save file must have been reset to be an empty one. 

I moved it to replace the old save file, so the original was lost, and the new save started off with "New Game" at the top, and continue wasn't an option so I knew my progress had been lost.

**Comment by codemonkey85** [comment]
> Edit: If I find it, how would you like me to send it to you?

You should be able to attach it to a comment in this thread.

**Comment by Luna-Karch** [comment]
I couldn't find it so I recreated the error with a new file, when attempting to open it with PKHeX it says it's unsupporte

**Comment by Luna-Karch** [comment]
[White_2.zip](https://github.com/codemonkey85/PKMDS-Blazor/files/14337716/White_2.zip)

**Comment by codemonkey85** [comment]
Thank you for sharing. I will look into this.

**Comment by Luna-Karch** [comment]
Any updates?

**Comment by codemonkey85** [comment]
Not yet. This is a hobby project, finding time to work on it is challenging.

**Comment by codemonkey85** [comment]
@Luna-Karch I started looking into this today. The save file you shared with me - is it the corrupted file? Can you share the original file you tried to load into PKMDS? That's the one I need to debug this issue.

**Comment by Luna-Karch** [comment]
The one I shared to you is the corrupted one yes. I would have to recreate the white 2.dsv file but I was able to reproduce the issue multiple times with any generic white 2.dsv

**Comment by arleypadua** [comment]
I faced the same issue while developing a [cross platform CLI](https://github.com/arleypadua/PKHeX.CLI)

It turns out that PKHeX.Core doesn't know the format of the file unless you specifically tell it what the file name is (including the file extension)

So, whenever it loads up a Desmume save, it will strip out the Desmume specific footer.

Without the footer, it is a totally valid save file, but invalid for Desmume

When Desmume sees a save without the footer, it will wipe out the whole save adding the footer back.

I solved it by passing down the file path when loading the file:

https://github.com/arleypadua/PKHeX.CLI/blob/ee9d7ddbb9b681b1cd295b312cb72f4a67c89c6e/src/PKHeX.Facade/Game.cs#L27

**Comment by anjeronett** [comment]
Issue also occurs on Platinum.
I did some more testing and the exported save file is completely incapable of writing new saves. It wipes after each reset.

**Comment by codemonkey85** [comment]
@ghost @anjeronett Thanks for the feedback. Sorry for the wait. The issue should be resolved now. Thanks for the tip, @arleypadua!
